FROM node:18 as build

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Étape 2 : Serve avec Nginx
FROM nginx:alpine

# Copie les fichiers statiques dans le répertoire public Nginx
COPY --from=build /app/dist /usr/share/nginx/html

# Supprime la config par défaut de nginx
RUN rm /etc/nginx/conf.d/default.conf

# Ajoute une config nginx personnalisée
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]